import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ChatMessage, UserRole } from '@/src/types';

type Receipt={userId:string;name:string;role:UserRole;deliveredAt?:string;readAt?:string};
const when=(v?:string)=>v?new Date(v).toLocaleString():'—';
export function MessageInfo({visible,message,receipts,onClose}:{visible:boolean;message:ChatMessage|null;receipts:Receipt[];onClose:()=>void}){
 if(!message)return null;
 const read=receipts.filter(r=>r.readAt);const delivered=receipts.filter(r=>!r.readAt&&r.deliveredAt);
 return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={s.page}><View style={s.header}><Pressable style={s.icon} onPress={onClose}><Ionicons name="close" size={25} color="#111827"/></Pressable><Text style={s.title}>Message info</Text></View><ScrollView contentContainerStyle={s.body}><View style={s.preview}><Text style={s.from}>{message.senderName}</Text><Text style={s.message}>{message.text||message.attachment?.name||'Attachment'}</Text><Text style={s.time}>Sent {when(message.createdAt)}</Text></View><Section title="Read by" icon="checkmark-done" rows={read} timeKey="readAt"/><Section title="Delivered to" icon="checkmark-done-outline" rows={delivered} timeKey="deliveredAt"/>{!read.length&&!delivered.length?<Text style={s.empty}>No participant receipts have synced yet.</Text>:null}</ScrollView></View></Modal>
}
function Section({title,icon,rows,timeKey}:{title:string;icon:any;rows:Receipt[];timeKey:'readAt'|'deliveredAt'}){if(!rows.length)return null;return <View style={s.section}><View style={s.sectionTitle}><Ionicons name={icon} size={19} color="#087F5B"/><Text style={s.label}>{title}</Text></View>{rows.map(r=><View key={r.userId} style={s.row}><View style={s.avatar}><Text style={s.initial}>{r.name.slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{r.name}</Text><Text style={s.role}>{r.role.replace('_',' ')}</Text></View><Text style={s.when}>{when(r[timeKey])}</Text></View>)}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F8FAFC'},header:{height:64,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderColor:'#E2E8F0',backgroundColor:'#FFF',paddingHorizontal:8},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:'900',color:'#111827'},body:{padding:16,gap:18},preview:{backgroundColor:'#ECFDF5',borderWidth:1,borderColor:'#A7F3D0',borderRadius:14,padding:14},from:{fontSize:12,fontWeight:'900',color:'#047857'},message:{fontSize:15,color:'#111827',marginTop:5},time:{fontSize:11,color:'#64748B',marginTop:8},section:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:14,overflow:'hidden'},sectionTitle:{flexDirection:'row',alignItems:'center',gap:8,padding:13,borderBottomWidth:1,borderColor:'#E2E8F0'},label:{fontSize:14,fontWeight:'900',color:'#111827'},row:{minHeight:68,flexDirection:'row',alignItems:'center',gap:10,padding:12,borderBottomWidth:1,borderColor:'#F1F5F9'},avatar:{width:40,height:40,borderRadius:20,backgroundColor:'#D1FAE5',alignItems:'center',justifyContent:'center'},initial:{fontWeight:'900',color:'#047857'},name:{fontWeight:'800',color:'#111827'},role:{fontSize:11,color:'#64748B',textTransform:'capitalize'},when:{fontSize:10,color:'#64748B',maxWidth:110,textAlign:'right'},empty:{textAlign:'center',color:'#64748B',padding:20}});
