import { useEffect, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { CatalogueRepository, type SearchableOfferItem } from '@/src/db/repositories/CatalogueRepository';
import type { BusinessActivity, BusinessStability, BusinessType, JunctionType, RelativeBusinessPosition } from '@/src/types';

export type BusinessCaptureValue = {
  name?: string; noVisibleName?: boolean; businessType: BusinessType; activity: BusinessActivity;
  stability?: BusinessStability; relativePosition?: RelativeBusinessPosition; shopNumber?: string;
  sectionName?: string; lineName?: string; primaryCategoryId?: string;
  offerings: { catalogueItemId?: string; pendingSuggestionId?: string; name: string; itemType: 'product' | 'service'; howEstablished: 'observed' | 'trader_confirmed' | 'both' | 'other' }[];
};

const businessTypes: BusinessType[] = ['shop','stall','kiosk','open_stand','workshop','service_point','restaurant_food_point','temporary_stand','mobile_trader','wholesale_outlet','other'];
const activities: BusinessActivity[] = ['sells_goods','provides_services','both'];
const junctionTypes: { value: JunctionType; label: string; glyph: string }[] = [
  { value:'t_junction', label:'T-Junction', glyph:'┬' }, { value:'cross_4way', label:'Cross / 4-Way', glyph:'┼' },
  { value:'y_fork', label:'Y / Fork', glyph:'Y' }, { value:'irregular_3way', label:'Irregular 3-Way', glyph:'⋔' },
  { value:'multi_way_complex', label:'Multi-Way / Complex', glyph:'✣' }, { value:'corner_bend', label:'Corner / Bend', glyph:'⌞' },
  { value:'path_end_dead_end', label:'Path End / Dead End', glyph:'⊣' }, { value:'other_unknown', label:'Other / Unknown', glyph:'?' },
];

export function NativeBusinessCapture({ visible, onClose, onSave }: { visible: boolean; onClose: () => void; onSave: (value: BusinessCaptureValue) => Promise<void> }) {
  const [step,setStep]=useState(1); const [busy,setBusy]=useState(false);
  const [businessType,setBusinessType]=useState<BusinessType>('shop'); const [activity,setActivity]=useState<BusinessActivity>('sells_goods');
  const [name,setName]=useState(''); const [shopNumber,setShopNumber]=useState(''); const [sectionName,setSectionName]=useState(''); const [lineName,setLineName]=useState('');
  const [relativePosition,setRelativePosition]=useState<RelativeBusinessPosition>('unclear'); const [stability,setStability]=useState<BusinessStability>('unknown');
  const [query,setQuery]=useState(''); const [results,setResults]=useState<SearchableOfferItem[]>([]); const [selected,setSelected]=useState<SearchableOfferItem[]>([]);
  useEffect(()=>{ if(visible && step===3) CatalogueRepository.search(query).then(setResults).catch(()=>setResults([])); },[visible,step,query]);
  const reset=()=>{setStep(1);setName('');setShopNumber('');setSectionName('');setLineName('');setQuery('');setSelected([]);};
  const close=()=>{reset();onClose();};
  return <Modal visible={visible} animationType="slide" onRequestClose={close}><View style={s.page}>
    <View style={s.header}><View><Text style={s.eyebrow}>ADD BUSINESS · {step}/4</Text><Text style={s.title}>{['Classification','Business details','Goods & services','Review & save'][step-1]}</Text></View><Pressable onPress={close} style={s.close}><Text style={s.closeText}>×</Text></Pressable></View>
    <ScrollView contentContainerStyle={s.body}>
      {step===1 && <><Text style={s.label}>Place type</Text><View style={s.grid}>{businessTypes.map(v=><Choice key={v} label={v.replaceAll('_',' ')} selected={businessType===v} onPress={()=>setBusinessType(v)}/>)}</View><Text style={s.label}>Activity</Text><View style={s.grid}>{activities.map(v=><Choice key={v} label={v.replaceAll('_',' ')} selected={activity===v} onPress={()=>setActivity(v)}/>)}</View></>}
      {step===2 && <><Field label="Displayed name (leave blank for No Visible Name)" value={name} onChangeText={setName}/><Field label="Shop / stall number" value={shopNumber} onChangeText={setShopNumber}/><Field label="Section / area" value={sectionName} onChangeText={setSectionName}/><Field label="Line / row / block" value={lineName} onChangeText={setLineName}/><Text style={s.label}>Position from current travel direction</Text><View style={s.grid}>{(['left','right','ahead','unclear'] as RelativeBusinessPosition[]).map(v=><Choice key={v} label={v} selected={relativePosition===v} onPress={()=>setRelativePosition(v)}/>)}</View></>}
      {step===3 && <><Field label="Search goods or services" value={query} onChangeText={setQuery}/><Text style={s.help}>Suggestions are shortcuts only. Nothing is selected automatically.</Text>{results.slice(0,12).map(item=><Pressable key={item.id} style={s.result} onPress={()=>setSelected(cur=>cur.some(x=>x.id===item.id)?cur.filter(x=>x.id!==item.id):[...cur,item])}><Text style={s.resultText}>{selected.some(x=>x.id===item.id)?'✓ ':''}{item.name}</Text><Text style={s.small}>{item.itemType}{item.isPendingSuggestion?' · pending suggestion':''}</Text></Pressable>)}</>}
      {step===4 && <><Text style={s.summary}>{name.trim()||'No Visible Name'}</Text><Text style={s.help}>{businessType.replaceAll('_',' ')} · {activity.replaceAll('_',' ')} · {selected.length} offering(s)</Text><Text style={s.label}>Stability</Text><View style={s.grid}>{(['permanent','semi_permanent','temporary','seasonal','mobile','unknown'] as BusinessStability[]).map(v=><Choice key={v} label={v.replaceAll('_',' ')} selected={stability===v} onPress={()=>setStability(v)}/>)}</View><Text style={s.help}>Photo remains optional at this migration checkpoint. Photo Declined / camera capture will be added with the native media adapter.</Text></>}
    </ScrollView>
    <View style={s.footer}>{step>1?<Pressable style={s.secondary} onPress={()=>setStep(x=>x-1)}><Text style={s.secondaryText}>Back</Text></Pressable>:null}{step<4?<Pressable style={s.primary} onPress={()=>setStep(x=>x+1)}><Text style={s.primaryText}>Continue</Text></Pressable>:<Pressable disabled={busy} style={s.primary} onPress={async()=>{setBusy(true);try{await onSave({name:name.trim()||undefined,noVisibleName:!name.trim(),businessType,activity,stability,relativePosition,shopNumber:shopNumber||undefined,sectionName:sectionName||undefined,lineName:lineName||undefined,offerings:selected.map(o=>({catalogueItemId:o.isPendingSuggestion?undefined:o.id,pendingSuggestionId:o.isPendingSuggestion?o.id:undefined,name:o.name,itemType:o.itemType,howEstablished:'observed'}))});reset();}finally{setBusy(false)}}}><Text style={s.primaryText}>{busy?'Saving…':'Save Business'}</Text></Pressable>}</View>
  </View></Modal>;
}

export function NativeJunctionPicker({ visible, onClose, onSave }: { visible:boolean; onClose:()=>void; onSave:(type:JunctionType)=>Promise<void> }) {
 const [busy,setBusy]=useState(false); return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.sheetBackdrop}><View style={s.sheet}><Text style={s.eyebrow}>ADD JUNCTION</Text><Text style={s.title}>What does it look like from above?</Text><View style={s.junctionGrid}>{junctionTypes.map(j=><Pressable disabled={busy} key={j.value} style={s.junction} onPress={async()=>{setBusy(true);try{await onSave(j.value);onClose();}finally{setBusy(false)}}}><Text style={s.glyph}>{j.glyph}</Text><Text style={s.junctionLabel}>{j.label}</Text></Pressable>)}</View><Pressable style={s.secondary} onPress={onClose}><Text style={s.secondaryText}>Cancel</Text></Pressable></View></View></Modal>;
}
function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,selected&&s.choiceSelected]}><Text style={[s.choiceText,selected&&s.choiceSelectedText]}>{label}</Text></Pressable>}
function Field(props:{label:string;value:string;onChangeText:(v:string)=>void}){return <View><Text style={s.label}>{props.label}</Text><TextInput {...props} style={s.input} placeholderTextColor="#6B7280"/></View>}
const s=StyleSheet.create({
 page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:20,paddingBottom:16,backgroundColor:'#FFFFFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',justifyContent:'space-between'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827',marginTop:4},close:{width:48,height:48,alignItems:'center',justifyContent:'center'},closeText:{fontSize:32,color:'#111827'},body:{padding:20,gap:14,paddingBottom:120},label:{fontSize:14,fontWeight:'800',color:'#111827',marginTop:8},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{minHeight:48,paddingHorizontal:14,justifyContent:'center',borderWidth:2,borderColor:'#9CA3AF',borderRadius:12,backgroundColor:'#FFFFFF'},choiceSelected:{borderColor:'#047857',backgroundColor:'#ECFDF5'},choiceText:{fontSize:14,fontWeight:'700',color:'#374151',textTransform:'capitalize'},choiceSelectedText:{color:'#065F46'},input:{minHeight:50,borderWidth:2,borderColor:'#9CA3AF',borderRadius:12,paddingHorizontal:14,fontSize:16,color:'#111827',backgroundColor:'#FFFFFF',marginTop:6},help:{fontSize:13,lineHeight:19,color:'#4B5563'},result:{minHeight:52,padding:12,borderWidth:1,borderColor:'#D1D5DB',borderRadius:10,backgroundColor:'#FFFFFF'},resultText:{fontSize:15,fontWeight:'800',color:'#111827'},small:{fontSize:12,color:'#4B5563',marginTop:2},summary:{fontSize:26,fontWeight:'900',color:'#111827'},footer:{position:'absolute',bottom:0,left:0,right:0,padding:16,flexDirection:'row',gap:10,backgroundColor:'#FFFFFF',borderTopWidth:2,borderColor:'#D1D5DB'},primary:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#047857'},primaryText:{color:'#FFFFFF',fontWeight:'900',fontSize:16},secondary:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center',borderRadius:12,borderWidth:2,borderColor:'#374151',backgroundColor:'#FFFFFF'},secondaryText:{color:'#111827',fontWeight:'900',fontSize:16},sheetBackdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,0.25)'},sheet:{backgroundColor:'#F7FAF8',padding:20,paddingBottom:32,borderTopLeftRadius:24,borderTopRightRadius:24},junctionGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginVertical:18},junction:{width:'48%',minHeight:112,borderWidth:2,borderColor:'#374151',borderRadius:14,backgroundColor:'#FFFFFF',alignItems:'center',justifyContent:'center',padding:10},glyph:{fontSize:48,lineHeight:54,fontWeight:'900',color:'#111827'},junctionLabel:{fontSize:13,fontWeight:'800',color:'#111827',textAlign:'center',marginTop:4}
});
