import { useEffect, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { PathRepository } from '@/src/db/repositories/PathRepository';
import type { JunctionBranch, LocalPathJunction } from '@/src/types';

type Row = { junction: LocalPathJunction; branch: JunctionBranch };

export function RemainingBranchesSheet({ visible, missionId, userId, onClose, onSelect }: { visible:boolean; missionId:string; userId:string; onClose:()=>void; onSelect:(row:Row)=>void }) {
 const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(false);
 const refresh=async()=>{setLoading(true);try{setRows(await PathRepository.getRemainingJunctionBranches(missionId));}finally{setLoading(false)}};
 useEffect(()=>{if(visible)refresh()},[visible,missionId]);
 const grouped=rows.reduce<Record<string,{junction:LocalPathJunction;branches:JunctionBranch[]}>>((acc,row)=>{const key=row.junction.id;if(!acc[key])acc[key]={junction:row.junction,branches:[]};acc[key].branches.push(row.branch);return acc},{});
 return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.page}><View style={s.header}><View><Text style={s.eyebrow}>CONTINUE MAPPING</Text><Text style={s.title}>Remaining junction branches</Text></View><Pressable onPress={onClose} style={s.close}><Text style={s.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={s.body}>
  {loading?<Text style={s.help}>Loading remaining branches…</Text>:Object.values(grouped).length===0?<View style={s.empty}><Text style={s.emptyTitle}>No remaining branches</Text><Text style={s.help}>Nothing currently marked unmapped or in progress for this mission.</Text></View>:Object.values(grouped).map(group=><View key={group.junction.id} style={s.card}><Text style={s.cardTitle}>{group.junction.operationalLabel}</Text><Text style={s.help}>{group.branches.length} branch{group.branches.length===1?'':'es'} remaining</Text>{group.branches.map(branch=><View key={branch.id} style={s.branch}><View style={{flex:1}}><Text style={s.branchTitle}>{branch.label}</Text><Text style={s.status}>{branch.status==='in_progress'?'IN PROGRESS':'UNMAPPED'}</Text></View><Pressable style={s.action} onPress={async()=>{await PathRepository.markBranchInProgress(branch.id,userId);onSelect({junction:group.junction,branch:{...branch,status:'in_progress'}});onClose()}}><Text style={s.actionText}>Map Branch</Text></Pressable></View>)}</View>)}
 </ScrollView></View></Modal>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,padding:20,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',justifyContent:'space-between'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827',marginTop:4},close:{width:48,height:48,alignItems:'center',justifyContent:'center'},closeText:{fontSize:32,color:'#111827'},body:{padding:20,gap:14},help:{fontSize:14,lineHeight:20,color:'#4B5563'},empty:{padding:24,borderWidth:2,borderColor:'#D1D5DB',borderRadius:14,backgroundColor:'#FFF'},emptyTitle:{fontSize:20,fontWeight:'900',color:'#111827',marginBottom:6},card:{padding:16,borderWidth:2,borderColor:'#9CA3AF',borderRadius:14,backgroundColor:'#FFF',gap:10},cardTitle:{fontSize:19,fontWeight:'900',color:'#111827'},branch:{flexDirection:'row',alignItems:'center',gap:10,paddingTop:10,borderTopWidth:1,borderColor:'#E5E7EB'},branchTitle:{fontSize:15,fontWeight:'800',color:'#111827'},status:{fontSize:11,fontWeight:'900',color:'#047857',marginTop:3},action:{minHeight:48,paddingHorizontal:14,alignItems:'center',justifyContent:'center',backgroundColor:'#047857',borderRadius:10},actionText:{color:'#FFF',fontWeight:'900'}});
