import { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { LocalPathJunction, RawGpsSample } from '@/src/types';

export function ReviewRestartSheet({visible,points,junctions,onClose,onPoint,onJunction}:{visible:boolean;points:RawGpsSample[];junctions:LocalPathJunction[];onClose:()=>void;onPoint:(id:string)=>Promise<void>;onJunction:(id:string)=>Promise<void>}){
 const [busy,setBusy]=useState(false); useEffect(()=>{if(!visible)setBusy(false)},[visible]);
 const confirm=(title:string,message:string,run:()=>Promise<void>)=>Alert.alert(title,message,[{text:'Cancel',style:'cancel'},{text:'Continue',style:'destructive',onPress:async()=>{setBusy(true);try{await run();onClose()}finally{setBusy(false)}}}]);
 const candidates=points.filter((_,i)=>i===0||i===points.length-1||i%Math.max(1,Math.floor(points.length/12))===0);
 return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.page}><View style={s.header}><View><Text style={s.eyebrow}>PATH REVIEW</Text><Text style={s.title}>Restart from earlier point</Text></View><Pressable onPress={onClose} style={s.close}><Text style={s.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={s.body}>
  <Text style={s.warning}>Everything recorded after the selected point/junction will be excluded from the final path, but retained in the audit history.</Text>
  {junctions.length?<><Text style={s.section}>JUNCTIONS</Text>{junctions.map(j=><Pressable disabled={busy} key={j.id} style={s.card} onPress={()=>confirm('Restart from '+j.operationalLabel,'Exclude all accepted path points and later junctions after this junction?',()=>onJunction(j.id))}><Text style={s.cardTitle}>{j.operationalLabel}</Text><Text style={s.help}>{(j.junctionType ?? 'unknown').replaceAll('_',' ')} · point #{j.sequenceNumber}</Text></Pressable>)}</>:null}
  <Text style={s.section}>RECORDED POINTS</Text><Text style={s.help}>Showing spaced checkpoints rather than every GPS sample.</Text>{candidates.map(p=><Pressable disabled={busy} key={p.id} style={s.card} onPress={()=>confirm('Restart from point #'+p.sequenceNumber,'Exclude all accepted path points after this checkpoint?',()=>onPoint(p.id))}><Text style={s.cardTitle}>Point #{p.sequenceNumber}</Text><Text style={s.help}>{p.latitude.toFixed(5)}, {p.longitude.toFixed(5)}</Text></Pressable>)}
 </ScrollView></View></Modal>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,padding:20,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',justifyContent:'space-between'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#047857'},title:{fontSize:23,fontWeight:'900',color:'#111827',marginTop:4},close:{width:48,height:48,alignItems:'center',justifyContent:'center'},closeText:{fontSize:32,color:'#111827'},body:{padding:18,gap:10,paddingBottom:50},warning:{padding:14,borderRadius:12,borderWidth:2,borderColor:'#F59E0B',backgroundColor:'#FFFBEB',fontSize:14,lineHeight:20,fontWeight:'700',color:'#78350F'},section:{fontSize:12,fontWeight:'900',letterSpacing:1.1,color:'#374151',marginTop:10},card:{minHeight:60,padding:13,borderWidth:2,borderColor:'#9CA3AF',borderRadius:12,backgroundColor:'#FFF',justifyContent:'center'},cardTitle:{fontSize:15,fontWeight:'900',color:'#111827'},help:{fontSize:13,lineHeight:19,color:'#4B5563',marginTop:3}});
