import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { listAdminUsers, setAdminUserActive, updateAdminUserRole, type AdminUser } from '@/src/native/adminService';
export default function AdminUsers(){
 const [items,setItems]=useState<AdminUser[]>([]);const load=useCallback(async()=>setItems(await listAdminUsers()),[]);useFocusEffect(useCallback(()=>{load()},[load]));
 const role=(u:AdminUser,r:AdminUser['role'])=>Alert.alert('Change role?',u.fullName+' → '+r.replace('_',' '),[{text:'Cancel',style:'cancel'},{text:'Confirm',onPress:async()=>{try{await updateAdminUserRole(u.id,r);await load()}catch(e){Alert.alert('Role change blocked',String(e))}}}]);
 const active=(u:AdminUser)=>Alert.alert(u.isActive?'Deactivate account?':'Reactivate account?',u.fullName,[{text:'Cancel',style:'cancel'},{text:'Confirm',style:u.isActive?'destructive':'default',onPress:async()=>{try{await setAdminUserActive(u.id,!u.isActive);await load()}catch(e){Alert.alert('Account change blocked',String(e))}}}]);
 return <View style={s.page}><Header/><ScrollView contentContainerStyle={s.body}>{items.map(u=><View key={u.id} style={[s.card,!u.isActive&&s.inactive]}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{u.fullName}</Text><Text style={s.help}>{u.email}</Text></View><Text style={s.status}>{u.isActive?'ACTIVE':'INACTIVE'}</Text></View><Text style={s.role}>ROLE · {u.role.replace('_',' ').toUpperCase()}</Text><View style={s.roles}>{(['mapper','team_lead','admin'] as const).map(r=><Pressable key={r} onPress={()=>r!==u.role&&role(u,r)} style={[s.chip,r===u.role&&s.chipActive]}><Text style={[s.chipText,r===u.role&&s.chipTextActive]}>{r.replace('_',' ')}</Text></Pressable>)}</View><Pressable style={[s.toggle,u.isActive&&s.danger]} onPress={()=>active(u)}><Text style={[s.toggleText,u.isActive&&s.dangerText]}>{u.isActive?'Deactivate':'Reactivate'}</Text></Pressable></View>)}</ScrollView></View>
}
function Header(){return <View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eye}>ADMIN · AUDITED</Text><Text style={s.title}>Users & Roles</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',alignItems:'center',gap:10},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eye:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:16,gap:10,paddingBottom:45},card:{padding:15,borderWidth:2,borderColor:'#D1D5DB',borderRadius:13,backgroundColor:'#FFF'},inactive:{backgroundColor:'#F3F4F6'},row:{flexDirection:'row',alignItems:'center',gap:8},name:{fontSize:16,fontWeight:'900',color:'#111827'},help:{fontSize:12,color:'#4B5563',marginTop:3},status:{fontSize:10,fontWeight:'900',color:'#047857'},role:{fontSize:11,fontWeight:'900',color:'#6B7280',marginTop:10},roles:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:8},chip:{minHeight:44,paddingHorizontal:11,borderWidth:2,borderColor:'#9CA3AF',borderRadius:10,alignItems:'center',justifyContent:'center'},chipActive:{borderColor:'#047857',backgroundColor:'#ECFDF5'},chipText:{fontSize:12,fontWeight:'800',color:'#374151',textTransform:'capitalize'},chipTextActive:{color:'#065F46'},toggle:{minHeight:46,marginTop:12,borderWidth:2,borderColor:'#047857',borderRadius:10,alignItems:'center',justifyContent:'center'},toggleText:{fontWeight:'900',color:'#065F46'},danger:{borderColor:'#B91C1C'},dangerText:{color:'#991B1B'}});
