import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { adminCounts } from '@/src/native/adminService';
import { requireNativeUserContext } from '@/src/native/userContext';
export default function AdminWorkspace(){
 const [counts,setCounts]=useState({users:0,teams:0,missions:0});const [ok,setOk]=useState<boolean|null>(null);
 const load=useCallback(async()=>{try{const u=await requireNativeUserContext();if(u.role!=='admin'){setOk(false);return}setOk(true);setCounts(await adminCounts())}catch{setOk(false)}},[]);useFocusEffect(useCallback(()=>{load()},[load]));
 if(ok===null)return <View style={s.center}><ActivityIndicator/></View>;if(!ok)return <View style={s.center}><Text style={s.title}>Admin access required</Text></View>;
 return <View style={s.page}><Header/><ScrollView contentContainerStyle={s.body}><View style={s.stats}><Stat n={counts.users} t="Users"/><Stat n={counts.teams} t="Teams"/><Stat n={counts.missions} t="Missions"/></View><Item t="Users & Roles" d="Roles, activation and account access" go={()=>router.push('/admin-users')}/><Item t="Teams" d="Field teams and membership" go={()=>router.push('/team-coordination')}/><Item t="Missions" d="Create and coordinate mapping missions" go={()=>router.push('/missions')}/><Item t="Catalogue" d="Categories, products, services and suggestions" go={()=>router.push('/catalogue-admin')}/><Item t="Field Issues" d="Operational issues requiring review" go={()=>router.push('/field-issues')}/><Item t="Announcements" d="Operational notices for field teams" go={()=>router.push('/chat')}/></ScrollView></View>
}
function Header(){return <View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eye}>ADMIN</Text><Text style={s.title}>Operations Workspace</Text></View></View>}
function Stat({n,t}:{n:number;t:string}){return <View style={s.stat}><Text style={s.num}>{n}</Text><Text style={s.small}>{t}</Text></View>}
function Item({t,d,go}:{t:string;d:string;go:()=>void}){return <Pressable style={s.item} onPress={go}><View style={{flex:1}}><Text style={s.itemTitle}>{t}</Text><Text style={s.help}>{d}</Text></View><Text style={s.chev}>›</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',alignItems:'center',gap:10},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eye:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:16,gap:10,paddingBottom:45},stats:{flexDirection:'row',gap:8},stat:{flex:1,minHeight:82,padding:10,borderWidth:2,borderColor:'#D1D5DB',borderRadius:13,backgroundColor:'#FFF',justifyContent:'center'},num:{fontSize:23,fontWeight:'900',color:'#111827'},small:{fontSize:11,fontWeight:'700',color:'#4B5563'},item:{minHeight:70,padding:14,borderWidth:2,borderColor:'#D1D5DB',borderRadius:13,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center'},itemTitle:{fontSize:16,fontWeight:'900',color:'#111827'},help:{fontSize:13,color:'#4B5563',marginTop:3},chev:{fontSize:28,color:'#6B7280'}});
