import { useCallback,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router,useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { ScreenHeader,ScreenSafeArea } from '@/src/native/ScreenScaffold';
import { listAdminMissions,type AdminMissionSummary } from '@/src/native/adminService';

export default function AdminMissions(){
 const[items,setItems]=useState<AdminMissionSummary[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await listAdminMissions())}catch(e){setError(e instanceof Error?e.message:'Could not load missions.')}finally{setLoading(false)}},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 return <ScreenSafeArea><ScreenHeader eyebrow="ADMIN · MISSIONS" title="Mission Operations" back right={<Pressable accessibilityLabel="Create mission" style={s.add} onPress={()=>router.push('/missions')}><Ionicons name="add" size={25} color="#FFF"/></Pressable>}/><ScrollView contentContainerStyle={s.body}>
  <View style={s.notice}><Text style={s.noticeTitle}>Administrative mission view</Text><Text style={s.help}>Manage the full mission inventory, teams and assignments here. Your own field assignments remain separate.</Text></View>
  {loading?<ActivityIndicator/>:error?<Text style={s.error}>{error}</Text>:items.length===0?<View style={s.empty}><Text style={s.cardTitle}>No missions created yet</Text><Text style={s.help}>Create the first mapping mission and assign its field team.</Text></View>:items.map(m=><View key={m.id} style={s.card}><View style={s.row}><Text style={s.status}>{m.status.replaceAll('_',' ').toUpperCase()}</Text><Text style={s.meta}>{m.memberCount} members · {m.areaCount} areas</Text></View><Text style={s.cardTitle}>{m.title}</Text><Text style={s.help}>{m.marketName||'Market not named'}{m.description?' · '+m.description:''}</Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>router.push({pathname:'/admin-mission-detail',params:{missionId:m.id}})}><Text style={s.secondaryText}>Manage</Text></Pressable><Pressable style={s.primary} onPress={()=>router.push({pathname:'/map',params:{missionId:m.id}})}><Text style={s.primaryText}>Open Map</Text></Pressable></View></View>)}
 </ScrollView></ScreenSafeArea>
}
const s=StyleSheet.create({body:{padding:16,gap:12,paddingBottom:44},add:{width:48,height:48,borderRadius:13,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},notice:{padding:15,borderRadius:14,borderWidth:2,borderColor:'#A7F3D0',backgroundColor:'#ECFDF5'},noticeTitle:{fontSize:15,fontWeight:'900',color:'#065F46'},help:{fontSize:13,lineHeight:19,color:'#4B5563',marginTop:4},error:{color:'#991B1B',fontWeight:'800'},empty:{padding:18,borderWidth:2,borderColor:'#D1D5DB',borderRadius:14,backgroundColor:'#FFF'},card:{padding:16,borderWidth:2,borderColor:'#D1D5DB',borderRadius:14,backgroundColor:'#FFF'},row:{flexDirection:'row',justifyContent:'space-between',gap:8},status:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#047857'},meta:{fontSize:11,fontWeight:'700',color:'#6B7280'},cardTitle:{fontSize:19,fontWeight:'900',color:'#111827',marginTop:7},actions:{flexDirection:'row',gap:8,marginTop:14},primary:{flex:1,minHeight:50,borderRadius:11,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{flex:1,minHeight:50,borderRadius:11,borderWidth:2,borderColor:'#047857',alignItems:'center',justifyContent:'center'},secondaryText:{color:'#065F46',fontWeight:'900'}});
