import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { CatalogueRepository } from '@/src/db/repositories/CatalogueRepository';
import { hydrateCatalogue, listPendingCloudSuggestions, listCanonicalCatalogueItems, mergeSuggestion, reviewSuggestion } from '@/src/native/catalogueService';
import { requireNativeUserContext } from '@/src/native/userContext';
export default function CatalogueAdmin(){
 const [cats,setCats]=useState<any[]>([]),[pending,setPending]=useState<any[]>([]),[canonical,setCanonical]=useState<any[]>([]),[mergeId,setMergeId]=useState<string|null>(null),[ok,setOk]=useState(false);
 const load=useCallback(async()=>{const u=await requireNativeUserContext();if(u.role!=='admin')return;setOk(true);await hydrateCatalogue().catch(()=>{});setCats(await CatalogueRepository.getCategories());setPending(await listPendingCloudSuggestions().catch(()=>[]));setCanonical(await listCanonicalCatalogueItems().catch(()=>[]))},[]);useFocusEffect(useCallback(()=>{load()},[load]));
 const review=(x:any,d:'approved'|'rejected')=>Alert.alert(d==='approved'?'Approve suggestion?':'Reject suggestion?',x.name,[{text:'Cancel',style:'cancel'},{text:d==='approved'?'Approve':'Reject',style:d==='rejected'?'destructive':'default',onPress:async()=>{try{await reviewSuggestion(x.id,d);await load()}catch(e){Alert.alert('Review failed',String(e))}}}]);
 const merge=(s:any,target:any)=>Alert.alert('Merge suggestion?',s.name+' → '+target.name,[{text:'Cancel',style:'cancel'},{text:'Merge',onPress:async()=>{try{await mergeSuggestion(s.id,target.id);setMergeId(null);await load()}catch(e){Alert.alert('Merge failed',String(e))}}}]);
 if(!ok)return <View style={s.center}><Text style={s.title}>Admin access required</Text></View>;
 return <View style={s.page}><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eye}>REFERENCE DATA</Text><Text style={s.title}>Catalogue</Text></View></View><ScrollView contentContainerStyle={s.body}><Text style={s.section}>CATEGORIES · {cats.length}</Text><View style={s.wrap}>{cats.map(c=><View key={c.id} style={s.chip}><Text style={s.chipText}>{c.name}</Text></View>)}</View><Text style={s.section}>PENDING SUGGESTIONS · {pending.length}</Text>{pending.length===0?<Text style={s.empty}>No pending mapper suggestions.</Text>:pending.map(x=><View key={x.id} style={s.card}><Text style={s.type}>{String(x.item_type).toUpperCase()}</Text><Text style={s.cardTitle}>{x.name}</Text><Text style={s.help}>Suggestion only — not verified catalogue data yet.</Text>{mergeId===x.id?<View style={s.mergeBox}><Text style={s.help}>Choose the verified {x.item_type} this suggestion means:</Text>{canonical.filter(i=>i.item_type===x.item_type).slice(0,12).map(i=><Pressable key={i.id} style={s.target} onPress={()=>merge(x,i)}><Text style={s.targetText}>{i.name}</Text></Pressable>)}</View>:null}<View style={s.actions}><Pressable style={s.merge} onPress={()=>setMergeId(mergeId===x.id?null:x.id)}><Text style={s.mergeText}>Merge</Text></Pressable><Pressable style={s.reject} onPress={()=>review(x,'rejected')}><Text style={s.rejectText}>Reject</Text></Pressable><Pressable style={s.approve} onPress={()=>review(x,'approved')}><Text style={s.approveText}>Approve</Text></Pressable></View></View>)}</ScrollView></View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',alignItems:'center',gap:10},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eye:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:16,gap:10,paddingBottom:45},section:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#6B7280',marginTop:7},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{minHeight:42,paddingHorizontal:12,borderWidth:2,borderColor:'#D1D5DB',borderRadius:10,backgroundColor:'#FFF',justifyContent:'center'},chipText:{fontWeight:'800',color:'#374151'},card:{padding:15,borderWidth:2,borderColor:'#D1D5DB',borderRadius:13,backgroundColor:'#FFF'},type:{fontSize:10,fontWeight:'900',color:'#047857'},cardTitle:{fontSize:17,fontWeight:'900',color:'#111827',marginTop:5},help:{fontSize:13,color:'#4B5563',marginTop:4},mergeBox:{marginTop:10,padding:10,borderRadius:10,borderWidth:2,borderColor:'#F59E0B',backgroundColor:'#FFFBEB',gap:6},target:{minHeight:44,paddingHorizontal:10,borderRadius:9,borderWidth:1,borderColor:'#D97706',justifyContent:'center',backgroundColor:'#FFF'},targetText:{fontWeight:'800',color:'#78350F'},actions:{flexDirection:'row',gap:6,marginTop:12},merge:{flex:1,minHeight:48,borderRadius:11,borderWidth:2,borderColor:'#D97706',alignItems:'center',justifyContent:'center'},mergeText:{color:'#92400E',fontWeight:'900'},approve:{flex:1,minHeight:48,borderRadius:11,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},approveText:{color:'#FFF',fontWeight:'900'},reject:{flex:1,minHeight:48,borderRadius:11,borderWidth:2,borderColor:'#B91C1C',alignItems:'center',justifyContent:'center'},rejectText:{color:'#991B1B',fontWeight:'900'},empty:{padding:20,textAlign:'center',color:'#6B7280'}});
