import { useCallback, useEffect, useState } from 'react';
import { ScreenSafeArea, ScreenHeader } from '@/src/native/ScreenScaffold';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { ChatRepository } from '@/src/db/repositories/ChatRepository';
import { getAssignedNativeMissions, requireNativeUserContext, type NativeUserContext } from '@/src/native/userContext';
import { runNativeSync } from '@/src/native/syncCoordinator';
import { subscribeOperationalData } from '@/src/native/operationalEvents';
import type { ChatChannel, ChatMessage } from '@/src/types';

export default function ChatScreen(){
 const [user,setUser]=useState<NativeUserContext|null>(null); const [channels,setChannels]=useState<ChatChannel[]>([]); const [active,setActive]=useState<ChatChannel|null>(null); const [messages,setMessages]=useState<ChatMessage[]>([]); const [text,setText]=useState(''); const [loading,setLoading]=useState(true);
 const loadChannels=useCallback(async()=>{const all=await ChatRepository.getAllChannels();setChannels(all);if(active){setMessages(await ChatRepository.getMessages(active.id))}},[active]);
 useFocusEffect(useCallback(()=>{loadChannels();return subscribeOperationalData(()=>{loadChannels()})},[loadChannels]));
 useEffect(()=>{let mounted=true;(async()=>{try{const u=await requireNativeUserContext();if(!mounted)return;setUser(u);const missions=await getAssignedNativeMissions(u.userId);for(const m of missions)await ChatRepository.getOrCreateChannel(m.title+' Comms','mission',undefined,m.id);await loadChannels()}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false}},[]);
 const open=async(c:ChatChannel)=>{setActive(c);setMessages(await ChatRepository.getMessages(c.id))};
 const send=async()=>{if(!user||!active||!text.trim())return;const body=text.trim();setText('');await ChatRepository.sendMessage({channelId:active.id,senderId:user.userId,senderName:user.fullName,senderRole:user.role,text:body});setMessages(await ChatRepository.getMessages(active.id));runNativeSync().catch(()=>{})};
 if(loading)return <View style={s.center}><ActivityIndicator/><Text style={s.help}>Loading mission chat…</Text></View>;
 return <ScreenSafeArea><ScreenHeader eyebrow="CHAT" title={active?.name||'Mission channels'} back={Boolean(active)}/>
 {active?<><ScrollView contentContainerStyle={s.messages}>{messages.length===0?<Text style={s.empty}>No messages yet.</Text>:messages.map(m=><View key={m.id} style={[s.bubble,m.senderId===user?.userId&&s.mine]}><Text style={s.sender}>{m.senderName} · {m.senderRole.replace('_',' ')}</Text><Text style={s.message}>{m.text}</Text><Text style={s.time}>{new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{m.syncStatus!=='synced'?' · saved locally':''}</Text></View>)}</ScrollView><View style={s.composer}><TextInput value={text} onChangeText={setText} placeholder="Message mission team…" placeholderTextColor="#6B7280" style={s.input} multiline/><Pressable style={s.send} onPress={send}><Text style={s.sendText}>Send</Text></Pressable></View></>:<ScrollView contentContainerStyle={s.list}>{channels.length===0?<Text style={s.empty}>No mission chat channels yet.</Text>:channels.map(c=><Pressable key={c.id} style={s.channel} onPress={()=>open(c)}><View style={{flex:1}}><Text style={s.channelTitle}>{c.name}</Text><Text style={s.help}>{c.lastMessageSnippet||'No messages yet'}</Text></View>{c.unreadCount?<View style={s.badge}><Text style={s.badgeText}>{c.unreadCount}</Text></View>:null}</Pressable>)}</ScrollView>}
 </ScreenSafeArea>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:18,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',gap:12,alignItems:'center'},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#047857'},title:{fontSize:23,fontWeight:'900',color:'#111827'},list:{padding:16,gap:10},channel:{minHeight:72,padding:14,borderRadius:13,borderWidth:2,borderColor:'#D1D5DB',backgroundColor:'#FFF',flexDirection:'row',alignItems:'center'},channelTitle:{fontSize:16,fontWeight:'900',color:'#111827'},help:{fontSize:13,color:'#4B5563',marginTop:3},badge:{minWidth:28,height:28,borderRadius:14,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},badgeText:{color:'#FFF',fontWeight:'900'},messages:{padding:14,gap:9,paddingBottom:22},empty:{fontSize:14,color:'#6B7280',padding:18,textAlign:'center'},bubble:{alignSelf:'flex-start',maxWidth:'88%',padding:12,borderRadius:13,borderWidth:1,borderColor:'#D1D5DB',backgroundColor:'#FFF'},mine:{alignSelf:'flex-end',borderColor:'#6EE7B7',backgroundColor:'#ECFDF5'},sender:{fontSize:11,fontWeight:'900',color:'#047857'},message:{fontSize:15,lineHeight:21,color:'#111827',marginTop:3},time:{fontSize:10,color:'#6B7280',marginTop:5},composer:{padding:12,borderTopWidth:2,borderColor:'#D1D5DB',backgroundColor:'#FFF',flexDirection:'row',gap:8,alignItems:'flex-end'},input:{flex:1,minHeight:50,maxHeight:120,borderWidth:2,borderColor:'#9CA3AF',borderRadius:12,paddingHorizontal:12,paddingVertical:10,color:'#111827',backgroundColor:'#FFF'},send:{minHeight:50,paddingHorizontal:18,borderRadius:12,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},sendText:{color:'#FFF',fontWeight:'900'}});
