import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { HandoverRepository } from '@/src/db/repositories/HandoverRepository';
import { requireNativeUserContext } from '@/src/native/userContext';
import { runNativeSync } from '@/src/native/syncCoordinator';
import type { Handover } from '@/src/types';

export default function Handovers(){
 const [items,setItems]=useState<Handover[]>([]);const [uid,setUid]=useState('');
 const load=useCallback(async()=>{const u=await requireNativeUserContext();setUid(u.userId);setItems(await HandoverRepository.getHandoversForUser(u.userId))},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const act=(x:Handover,status:'accepted'|'declined')=>Alert.alert(status==='accepted'?'Accept handover?':'Decline handover?',x.areaName,[{text:'Cancel',style:'cancel'},{text:status==='accepted'?'Accept':'Decline',onPress:async()=>{const ok=await HandoverRepository.updateStatus(x.id,status);if(!ok)Alert.alert('Assignment changed','This handover is stale because the area assignment changed.');await load();runNativeSync().then(load).catch(()=>{})}}]);
 return <View style={s.page}><Header/><ScrollView contentContainerStyle={s.body}>{items.length===0?<Text style={s.empty}>No handovers involving you.</Text>:items.map(x=><View key={x.id} style={s.card}><View style={s.row}><Text style={s.status}>{x.status.toUpperCase()}{x.status==='accepted'&&x.syncStatus!=='synced'?' · PENDING SYNC':''}</Text><Text style={s.meta}>{x.areaName}</Text></View><Text style={s.title}>{x.fromUserId===uid?'To '+x.toUserName:'From '+x.fromUserName}</Text><Text style={s.help}>{x.notes||'Continue the remaining mapping work from the agreed field point.'}</Text><Text style={s.meta}>{x.stallsCountAtHandover} businesses · {x.pathsCountAtHandover} paths at handover</Text>{x.toUserId===uid&&x.status==='pending'?<View style={s.actions}><Pressable style={s.secondary} onPress={()=>act(x,'declined')}><Text style={s.secondaryText}>Decline</Text></Pressable><Pressable style={s.primary} onPress={()=>act(x,'accepted')}><Text style={s.primaryText}>Accept</Text></Pressable></View>:null}</View>)}</ScrollView></View>
}
function Header(){return <View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eyebrow}>FIELD CONTINUITY</Text><Text style={s.headerTitle}>Handovers</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',alignItems:'center',gap:10},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},headerTitle:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:16,gap:10,paddingBottom:45},card:{padding:15,borderWidth:2,borderColor:'#D1D5DB',borderRadius:13,backgroundColor:'#FFF'},row:{flexDirection:'row',justifyContent:'space-between'},status:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#047857'},title:{fontSize:17,fontWeight:'900',color:'#111827',marginTop:6},help:{fontSize:13,lineHeight:19,color:'#374151',marginTop:5},meta:{fontSize:11,color:'#6B7280',marginTop:6},actions:{flexDirection:'row',gap:8,marginTop:12},primary:{flex:1,minHeight:48,backgroundColor:'#047857',borderRadius:11,alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{flex:1,minHeight:48,borderWidth:2,borderColor:'#6B7280',borderRadius:11,alignItems:'center',justifyContent:'center'},secondaryText:{color:'#374151',fontWeight:'900'},empty:{padding:25,textAlign:'center',fontSize:15,color:'#6B7280'}});
