import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ScreenHeader, ScreenSafeArea } from '@/src/native/ScreenScaffold';
import { getAssignedNativeMissions, requireNativeUserContext, type NativeMissionContext } from '@/src/native/userContext';
import { MissionRepository } from '@/src/db/repositories/MissionRepository';

export default function MissionDetail(){
 const {missionId}=useLocalSearchParams<{missionId:string}>();const [m,setM]=useState<NativeMissionContext|null>(null);const [area,setArea]=useState<any>(null);const [local,setLocal]=useState<any>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const u=await requireNativeUserContext();const found=(await getAssignedNativeMissions(u.userId)).find(x=>x.id===missionId)||null;setM(found);if(found){setLocal(await MissionRepository.getMissionById(found.id));const a=await MissionRepository.getAreaAssignments(found.id);setArea(a.find(x=>x.assignedToUserId===u.userId)||null)}}finally{setLoading(false)}})()},[missionId]);
 if(loading)return <View style={s.center}><ActivityIndicator/></View>;
 if(!m)return <View style={s.center}><Text style={s.title}>Mission unavailable</Text><Text style={s.help}>This mission is not assigned to your account.</Text><Pressable style={s.secondary} onPress={()=>router.replace('/missions')}><Text style={s.secondaryText}>Back to Missions</Text></Pressable></View>;
 const instructions=area?.notes||local?.description||m.description;
 const canManage=Boolean(local&&(local.createdBy||local.leadUserId));
 const finish=async()=>{const result=await MissionRepository.finishMission(m.id);if(!result.ok){Alert.alert('Mission cannot be finished yet',result.reason||'Review the mission requirements and try again.');return}Alert.alert('Mission completed','The mission has been marked completed.');router.replace('/missions')};
 const remove=()=>Alert.alert('Delete mission?','This permanently removes this mission and its local coordination data. This action cannot be undone.',[{text:'Cancel',style:'cancel'},{text:'Delete mission',style:'destructive',onPress:async()=>{await MissionRepository.deleteMission(m.id);router.replace('/missions')}}]);
 return <ScreenSafeArea><ScreenHeader eyebrow="MY FIELD MISSION" title={m.status.replaceAll('_',' ')} back/><ScrollView contentContainerStyle={s.body}><Text style={s.title}>{m.title}</Text><Info label="Market" value={local?.marketName||'Assigned market'}/><Info label="Assigned area" value={area?.areaName||'General / mission-wide'}/><Info label="Your role" value={m.roleInMission.replace('_',' ')}/><Info label="Starting point" value={area?.startingPointLabel||'Use mission map / field instruction'}/>{instructions?<Info label="Instructions" value={instructions}/>:null}<View style={s.note}><Text style={s.noteText}>The assigned starting point is an instruction. Your actual GPS start is recorded separately when mapping begins.</Text></View><Pressable style={s.primary} onPress={()=>router.push({pathname:'/map',params:{missionId:m.id}})}><Text style={s.primaryText}>Start / Resume Mapping</Text></Pressable><View style={s.actions}><Pressable style={s.secondary} onPress={()=>router.push('/chat')}><Text style={s.secondaryText}>Mission Chat</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push({pathname:'/send-handover',params:{missionId:m.id}})}><Text style={s.secondaryText}>Handover</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push({pathname:'/map',params:{missionId:m.id}})}><Text style={s.secondaryText}>Show on Map</Text></Pressable></View>{canManage?<View style={s.manage}><Text style={s.manageTitle}>Mission management</Text><Pressable style={s.finish} onPress={finish}><Text style={s.finishText}>Finish Mission</Text></Pressable><Pressable style={s.edit} onPress={()=>router.push({pathname:'/admin-mission-detail',params:{missionId:m.id}})}><Text style={s.editText}>Update Mission</Text></Pressable><Pressable style={s.delete} onPress={remove}><Text style={s.deleteText}>Delete Mission</Text></Pressable></View>:null}</ScrollView></ScreenSafeArea>
}
function Info({label,value}:{label:string;value:string}){return <View style={s.info}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({manage:{marginTop:12,padding:14,borderRadius:14,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',gap:9},manageTitle:{fontSize:13,fontWeight:'900',color:'#334155',marginBottom:2},finish:{minHeight:50,borderRadius:11,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},finishText:{color:'#FFF',fontWeight:'900'},edit:{minHeight:50,borderRadius:11,borderWidth:2,borderColor:'#047857',alignItems:'center',justifyContent:'center'},editText:{color:'#047857',fontWeight:'900'},delete:{minHeight:50,borderRadius:11,borderWidth:1,borderColor:'#FCA5A5',backgroundColor:'#FEF2F2',alignItems:'center',justifyContent:'center'},deleteText:{color:'#B91C1C',fontWeight:'900'},page:{flex:1,backgroundColor:'#F7FAF8'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',gap:10,alignItems:'center'},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},headerTitle:{fontSize:15,fontWeight:'900',color:'#374151',textTransform:'uppercase'},body:{padding:18,gap:11,paddingBottom:45},title:{fontSize:27,fontWeight:'900',color:'#111827',marginBottom:5},info:{padding:14,borderWidth:2,borderColor:'#D1D5DB',borderRadius:13,backgroundColor:'#FFF'},label:{fontSize:11,fontWeight:'900',letterSpacing:.8,color:'#6B7280',textTransform:'uppercase'},value:{fontSize:15,lineHeight:21,fontWeight:'700',color:'#111827',marginTop:4},note:{padding:13,borderRadius:12,backgroundColor:'#FFFBEB',borderWidth:2,borderColor:'#F59E0B'},noteText:{fontSize:13,lineHeight:19,color:'#78350F',fontWeight:'700'},primary:{minHeight:54,borderRadius:12,backgroundColor:'#047857',alignItems:'center',justifyContent:'center',marginTop:5},primaryText:{color:'#FFF',fontWeight:'900',fontSize:15},actions:{flexDirection:'row',flexWrap:'wrap',gap:9},secondary:{flex:1,minHeight:50,paddingHorizontal:12,borderRadius:11,borderWidth:2,borderColor:'#047857',alignItems:'center',justifyContent:'center'},secondaryText:{color:'#065F46',fontWeight:'900'},help:{fontSize:14,color:'#4B5563',marginVertical:10,textAlign:'center'}});
