import { useCallback, useState } from 'react';
import { ScreenSafeArea, ScreenHeader } from '@/src/native/ScreenScaffold';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { getAssignedNativeMissions, requireNativeUserContext, type NativeMissionContext } from '@/src/native/userContext';
import { MissionRepository } from '@/src/db/repositories/MissionRepository';

type Enriched=NativeMissionContext&{area?:string;instructions?:string;marketName?:string};
export default function MissionsScreen(){
 const [items,setItems]=useState<Enriched[]>([]);const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{const u=await requireNativeUserContext();const cloud=await getAssignedNativeMissions(u.userId);const out:Enriched[]=[];for(const m of cloud){const local=await MissionRepository.getMissionById(m.id);const areas=await MissionRepository.getAreaAssignments(m.id);const mine=areas.find(a=>a.assignedToUserId===u.userId);out.push({...m,marketName:local?.marketName,area:mine?.areaName,instructions:mine?.notes||local?.description||m.description||undefined})}setItems(out)}finally{setLoading(false)}},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 if(loading)return <View style={s.center}><ActivityIndicator/><Text style={s.help}>Loading assigned missions…</Text></View>;
 return <ScreenSafeArea><ScreenHeader eyebrow="MISSIONS" title="My field work"/><ScrollView contentContainerStyle={s.body}>{items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No Active Mission</Text><Text style={s.help}>When you are assigned to a mapping mission, it will appear here.</Text></View>:items.map(m=><View key={m.id} style={s.card}><View style={s.row}><Text style={s.status}>{m.status.replaceAll('_',' ').toUpperCase()}</Text><Text style={s.role}>{m.roleInMission}</Text></View><Text style={s.cardTitle}>{m.title}</Text><Text style={s.help}>{m.marketName||'Assigned market'}{m.area?' · '+m.area:''}</Text>{m.instructions?<Text style={s.instructions} numberOfLines={2}>{m.instructions}</Text>:null}<View style={s.actions}><Pressable style={s.secondary} onPress={()=>router.push({pathname:'/mission-detail',params:{missionId:m.id}})}><Text style={s.secondaryText}>View Mission</Text></Pressable><Pressable style={s.primary} onPress={()=>router.push({pathname:'/map',params:{missionId:m.id}})}><Text style={s.primaryText}>Start / Resume</Text></Pressable></View></View>)}</ScrollView></ScreenSafeArea>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:18,paddingBottom:16,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#047857'},title:{fontSize:27,fontWeight:'900',color:'#111827',marginTop:3},body:{padding:16,gap:12,paddingBottom:40},empty:{padding:20,borderWidth:2,borderColor:'#D1D5DB',borderRadius:15,backgroundColor:'#FFF'},emptyTitle:{fontSize:20,fontWeight:'900',color:'#111827'},card:{padding:16,borderRadius:15,borderWidth:2,borderColor:'#D1D5DB',backgroundColor:'#FFF'},row:{flexDirection:'row',justifyContent:'space-between'},status:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#047857'},role:{fontSize:11,fontWeight:'800',color:'#6B7280',textTransform:'uppercase'},cardTitle:{fontSize:19,fontWeight:'900',color:'#111827',marginTop:7},help:{fontSize:13,lineHeight:19,color:'#4B5563',marginTop:4},instructions:{fontSize:13,lineHeight:19,color:'#374151',marginTop:9},actions:{flexDirection:'row',gap:8,marginTop:14},primary:{flex:1,minHeight:50,borderRadius:11,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{flex:1,minHeight:50,borderRadius:11,borderWidth:2,borderColor:'#047857',alignItems:'center',justifyContent:'center'},secondaryText:{color:'#065F46',fontWeight:'900'}});
