import { useCallback, useState } from 'react';
import { useFocusEffect, router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { OutboxRepository } from '@/src/db/repositories/OutboxRepository';
import { MediaUploadRepository } from '@/src/db/repositories/MediaUploadRepository';
import { retryNativeSync, runNativeSync, type NativeSyncSnapshot } from '@/src/native/syncCoordinator';
import type { MediaUploadQueueItem, OutboxQueueItem } from '@/src/types';

export default function OfflineDataScreen(){
 const [outbox,setOutbox]=useState<OutboxQueueItem[]>([]); const [media,setMedia]=useState<MediaUploadQueueItem[]>([]); const [sync,setSync]=useState<NativeSyncSnapshot|null>(null); const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setOutbox(await OutboxRepository.getQueue());setMedia(await MediaUploadRepository.getPending())},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const run=async(retry=false)=>{setBusy(true);try{setSync(await (retry?retryNativeSync():runNativeSync()));await load()}finally{setBusy(false)}};
 const failed=outbox.filter(x=>x.status==='failed').length+media.filter(x=>x.status==='failed').length;
 return <View style={s.page}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eyebrow}>OFFLINE DATA</Text><Text style={s.title}>Saved on this device</Text></View></View><ScrollView contentContainerStyle={s.body}>
  <View style={s.banner}><Text style={s.bannerTitle}>{outbox.length+media.length===0?'Everything is synced':'Your field work is safe locally'}</Text><Text style={s.help}>{outbox.length} data change(s) · {media.length} media upload(s){failed?' · '+failed+' need retry':''}</Text></View>
  <View style={s.actions}><Pressable disabled={busy} style={s.primary} onPress={()=>run(false)}><Text style={s.primaryText}>{busy?'Syncing…':'Sync Now'}</Text></Pressable>{failed?<Pressable disabled={busy} style={s.secondary} onPress={()=>run(true)}><Text style={s.secondaryText}>Retry Failed</Text></Pressable>:null}</View>
  {sync?.lastError?<Text style={s.error}>{sync.lastError}</Text>:null}
  <Text style={s.section}>DATA CHANGES</Text>{outbox.length===0?<Text style={s.help}>No pending relational changes.</Text>:outbox.map(x=><QueueCard key={x.id} title={friendly(x.tableName)} status={x.status} detail={x.action+' · '+x.recordId.slice(-8)} error={x.errorMessage} retries={x.retryCount}/>)}
  <Text style={s.section}>MEDIA</Text>{media.length===0?<Text style={s.help}>No pending photos.</Text>:media.map(x=><QueueCard key={x.id} title="Business photo" status={x.status} detail={x.entityId.slice(-8)} error={x.errorMessage} retries={x.retryCount}/>)}
 </ScrollView></View>
}
function friendly(t:string){return ({businesses:'Business',market_paths:'Path',path_junctions:'Junction',junction_branches:'Junction branch',local_field_issues:'Field issue',local_market_places:'Place'} as Record<string,string>)[t]||'Saved field record'}
function QueueCard({title,status,detail,error,retries}:{title:string;status:string;detail:string;error?:string;retries:number}){return <View style={[s.card,status==='failed'&&s.cardFailed]}><View style={s.row}><Text style={s.cardTitle}>{title}</Text><Text style={[s.status,status==='failed'&&s.statusFailed]}>{status.toUpperCase()}</Text></View><Text style={s.help}>{detail} · attempt {retries}/5</Text>{error?<Text style={s.error}>{humanError(error)}</Text>:null}</View>}
function humanError(e:string){if(e.includes('LOCAL_MEDIA_FILE_MISSING'))return 'The staged photo file is missing from this device.';if(e.includes('AUTH'))return 'Sign in again before syncing this item.';if(e.includes('network')||e.includes('fetch'))return 'Network unavailable. Your work remains saved locally.';return e.length>180?e.slice(0,177)+'…':e}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:18,paddingBottom:16,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',gap:12,alignItems:'center'},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:18,gap:12,paddingBottom:48},banner:{padding:16,borderRadius:14,borderWidth:2,borderColor:'#047857',backgroundColor:'#ECFDF5'},bannerTitle:{fontSize:18,fontWeight:'900',color:'#065F46'},help:{fontSize:13,lineHeight:19,color:'#4B5563',marginTop:3},actions:{flexDirection:'row',gap:10},primary:{minHeight:50,flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#047857',borderRadius:12},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{minHeight:50,flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF',borderWidth:2,borderColor:'#374151',borderRadius:12},secondaryText:{color:'#111827',fontWeight:'900'},section:{marginTop:10,fontSize:12,fontWeight:'900',letterSpacing:1.1,color:'#374151'},card:{padding:14,borderRadius:12,borderWidth:2,borderColor:'#D1D5DB',backgroundColor:'#FFF'},cardFailed:{borderColor:'#FCA5A5',backgroundColor:'#FEF2F2'},row:{flexDirection:'row',justifyContent:'space-between',gap:10},cardTitle:{fontSize:15,fontWeight:'900',color:'#111827'},status:{fontSize:11,fontWeight:'900',color:'#047857'},statusFailed:{color:'#B91C1C'},error:{fontSize:13,lineHeight:19,color:'#991B1B',marginTop:6}});
