import { useCallback, useState } from 'react';
import { ScreenSafeArea, ScreenHeader } from '@/src/native/ScreenScaffold';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { RevisitRepository } from '@/src/db/repositories/RevisitRepository';
import { runNativeSync } from '@/src/native/syncCoordinator';
import { requireNativeUserContext } from '@/src/native/userContext';
import type { Revisit } from '@/src/types';

export default function RevisitsScreen(){
 const [items,setItems]=useState<Revisit[]>([]); const [uid,setUid]=useState('');
 const load=useCallback(async()=>{const u=await requireNativeUserContext();setUid(u.userId);const all=await RevisitRepository.getAll();setItems(all.filter(x=>x.status==='open'&&(!x.assignedTo||x.assignedTo===u.userId)))},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const resolve=(x:Revisit)=>Alert.alert('Mark revisit complete?',x.entityTitle||'This field item',[{text:'Cancel',style:'cancel'},{text:'Complete',onPress:async()=>{await RevisitRepository.resolve(x.id,uid);await load();runNativeSync().catch(()=>{})}}]);
 return <ScreenSafeArea><ScreenHeader eyebrow="FIELD FOLLOW-UP" title="Revisits" back/><ScrollView contentContainerStyle={s.body}>{items.length===0?<Text style={s.empty}>No open revisits assigned to you.</Text>:items.map(x=><View key={x.id} style={s.card}><Text style={s.type}>{x.reason.replaceAll('_',' ').toUpperCase()}</Text><Text style={s.title}>{x.entityTitle||x.entityType.replace('_',' ')}</Text>{x.notes?<Text style={s.help}>{x.notes}</Text>:null}<Text style={s.meta}>{x.entityType.replace('_',' ')} · saved {x.syncStatus==='synced'?'to cloud':'locally'}</Text><View style={s.row}><Pressable style={s.secondary} onPress={()=>router.push('/map')}><Text style={s.secondaryText}>Show on Map</Text></Pressable><Pressable style={s.primary} onPress={()=>resolve(x)}><Text style={s.primaryText}>Complete</Text></Pressable></View></View>)}</ScrollView></ScreenSafeArea>
}
function Header({title}:{title:string}){return <View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eyebrow}>FIELD FOLLOW-UP</Text><Text style={s.headerTitle}>{title}</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',alignItems:'center',gap:10},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},headerTitle:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:16,gap:10,paddingBottom:45},card:{padding:15,borderWidth:2,borderColor:'#D1D5DB',borderRadius:13,backgroundColor:'#FFF'},type:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#B45309'},title:{fontSize:17,fontWeight:'900',color:'#111827',marginTop:5},help:{fontSize:13,lineHeight:19,color:'#4B5563',marginTop:5},meta:{fontSize:11,color:'#6B7280',marginTop:9},row:{flexDirection:'row',gap:8,marginTop:12},primary:{flex:1,minHeight:48,backgroundColor:'#047857',borderRadius:11,alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{flex:1,minHeight:48,borderWidth:2,borderColor:'#047857',borderRadius:11,alignItems:'center',justifyContent:'center'},secondaryText:{color:'#065F46',fontWeight:'900'},empty:{padding:25,textAlign:'center',fontSize:15,color:'#6B7280'}});
