import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { MissionRepository } from '@/src/db/repositories/MissionRepository';
import { HandoverRepository } from '@/src/db/repositories/HandoverRepository';
import { requireNativeUserContext } from '@/src/native/userContext';
import { runNativeSync } from '@/src/native/syncCoordinator';
import type { MissionAreaAssignment, MissionMember } from '@/src/types';

export default function SendHandover(){
 const {missionId}=useLocalSearchParams<{missionId?:string}>();const [uid,setUid]=useState('');const [name,setName]=useState('');const [areas,setAreas]=useState<MissionAreaAssignment[]>([]);const [members,setMembers]=useState<MissionMember[]>([]);const [areaId,setAreaId]=useState('');const [toId,setToId]=useState('');const [continueFrom,setContinueFrom]=useState('');const [remaining,setRemaining]=useState('');const [note,setNote]=useState('');
 useEffect(()=>{(async()=>{const u=await requireNativeUserContext();setUid(u.userId);setName(u.fullName);if(!missionId)return;const [a,m]=await Promise.all([MissionRepository.getAreaAssignments(missionId),MissionRepository.getMembers(missionId)]);const mine=a.filter(x=>x.assignedToUserId===u.userId);setAreas(mine);setMembers(m.filter(x=>x.userId!==u.userId));if(mine[0])setAreaId(mine[0].areaId)})()},[missionId]);
 const area=useMemo(()=>areas.find(x=>x.areaId===areaId),[areas,areaId]);const teammate=useMemo(()=>members.find(x=>x.userId===toId),[members,toId]);
 const send=async()=>{if(!missionId||!area||!teammate)return Alert.alert('Choose area and teammate','Both are required for a handover.');const mission=await MissionRepository.getMissionById(missionId);const notes=[continueFrom&&'Continue from: '+continueFrom,remaining&&'Still remaining: '+remaining,note].filter(Boolean).join('\n');await HandoverRepository.createHandover({missionId,missionTitle:mission?.title,areaId:area.areaId,areaName:area.areaName,fromUserId:uid,fromUserName:name,toUserId:teammate.userId,toUserName:teammate.userName,notes});runNativeSync().catch(()=>{});Alert.alert('Handover sent','The teammate has been notified. Your local record is safe even if you are offline.',[{text:'Done',onPress:()=>router.back()}])};
 return <View style={s.page}><Header/><ScrollView contentContainerStyle={s.body}><Text style={s.label}>AREA</Text><View style={s.options}>{areas.map(a=><Choice key={a.areaId} text={a.areaName||'Area'} active={a.areaId===areaId} onPress={()=>setAreaId(a.areaId)}/>)}</View><Text style={s.label}>CONTINUE FROM</Text><TextInput style={s.input} value={continueFrom} onChangeText={setContinueFrom} placeholder="e.g. J021 or North gate passage" placeholderTextColor="#6B7280"/><Text style={s.label}>TO TEAMMATE</Text><View style={s.options}>{members.map(m=><Choice key={m.userId} text={m.userName||'Team member'} active={m.userId===toId} onPress={()=>setToId(m.userId)}/>)}</View><Text style={s.label}>STILL REMAINING</Text><TextInput style={[s.input,s.multi]} multiline value={remaining} onChangeText={setRemaining} placeholder="e.g. 2 revisits, one unmapped passage" placeholderTextColor="#6B7280"/><Text style={s.label}>OPTIONAL NOTE</Text><TextInput style={[s.input,s.multi]} multiline value={note} onChangeText={setNote} placeholder="Anything the next mapper should know" placeholderTextColor="#6B7280"/><Pressable style={s.primary} onPress={send}><Text style={s.primaryText}>Send Handover</Text></Pressable></ScrollView></View>
}
function Choice({text,active,onPress}:{text:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,active&&s.choiceActive]}><Text style={[s.choiceText,active&&s.choiceTextActive]}>{text}</Text></Pressable>}
function Header(){return <View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eyebrow}>FIELD CONTINUITY</Text><Text style={s.title}>Send Handover</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',alignItems:'center',gap:10},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:17,gap:9,paddingBottom:50},label:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#374151',marginTop:8},options:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{minHeight:46,paddingHorizontal:13,borderRadius:11,borderWidth:2,borderColor:'#9CA3AF',backgroundColor:'#FFF',alignItems:'center',justifyContent:'center'},choiceActive:{borderColor:'#047857',backgroundColor:'#ECFDF5'},choiceText:{fontWeight:'800',color:'#374151'},choiceTextActive:{color:'#065F46'},input:{minHeight:50,borderWidth:2,borderColor:'#9CA3AF',borderRadius:11,paddingHorizontal:12,paddingVertical:10,backgroundColor:'#FFF',color:'#111827'},multi:{minHeight:84,textAlignVertical:'top'},primary:{minHeight:54,borderRadius:12,backgroundColor:'#047857',alignItems:'center',justifyContent:'center',marginTop:10},primaryText:{color:'#FFF',fontWeight:'900',fontSize:15}});
