import { useCallback, useState } from 'react';
import { ScreenSafeArea, ScreenHeader } from '@/src/native/ScreenScaffold';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { requireNativeUserContext, getAssignedNativeMissions } from '@/src/native/userContext';
import { MissionRepository } from '@/src/db/repositories/MissionRepository';
import { HandoverRepository } from '@/src/db/repositories/HandoverRepository';
import { FieldIssueRepository } from '@/src/db/repositories/FieldIssueRepository';

type Card={id:string;title:string;sub:string;meta:string};
export default function TeamCoordination(){
 const [areas,setAreas]=useState<Card[]>([]);const [pending,setPending]=useState(0);const [issues,setIssues]=useState(0);const [allowed,setAllowed]=useState<boolean|null>(null);
 const load=useCallback(async()=>{const u=await requireNativeUserContext();if(u.role==='mapper'){setAllowed(false);return}setAllowed(true);const missions=await getAssignedNativeMissions(u.userId);const cards:Card[]=[];for(const m of missions){const aa=await MissionRepository.getAreaAssignments(m.id);for(const a of aa)cards.push({id:m.id+':'+a.areaId,title:a.areaName||'Market area',sub:a.assignedToUserName||'Unassigned',meta:m.title+' · '+a.status.replace('_',' ')})}setAreas(cards);const h=await HandoverRepository.getAllHandovers();setPending(h.filter(x=>x.status==='pending').length);const fi=await FieldIssueRepository.getAllIssues();setIssues(fi.filter(x=>x.status==='open').length)},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 if(allowed===false)return <View style={s.center}><Text style={s.title}>Coordination access required</Text><Text style={s.help}>Team coordination is available to Team Leads and Admins.</Text></View>;
 return <ScreenSafeArea><ScreenHeader eyebrow="TEAM LEAD" title="Field Coordination" back/><ScrollView contentContainerStyle={s.body}><View style={s.stats}><Stat n={areas.length} label="Areas"/><Stat n={pending} label="Pending handovers"/><Stat n={issues} label="Open issues"/></View><View style={s.actions}><Action title="Handovers" onPress={()=>router.push('/handovers')}/><Action title="Field Issues" onPress={()=>router.push('/field-issues')}/></View><Text style={s.section}>AREA ASSIGNMENTS</Text>{areas.length===0?<Text style={s.empty}>No cached area assignments yet.</Text>:areas.map(a=><View key={a.id} style={s.card}><Text style={s.cardTitle}>{a.title}</Text><Text style={s.help}>{a.sub}</Text><Text style={s.meta}>{a.meta}</Text></View>)}</ScrollView></ScreenSafeArea>
}
function Stat({n,label}:{n:number;label:string}){return <View style={s.stat}><Text style={s.num}>{n}</Text><Text style={s.statLabel}>{label}</Text></View>}
function Action({title,onPress}:{title:string;onPress:()=>void}){return <Pressable style={s.action} onPress={onPress}><Text style={s.actionText}>{title}</Text></Pressable>}
function Header(){return <View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.eyebrow}>TEAM LEAD</Text><Text style={s.title}>Field Coordination</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24,backgroundColor:'#F7FAF8'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:14,backgroundColor:'#FFF',borderBottomWidth:2,borderColor:'#D1D5DB',flexDirection:'row',alignItems:'center',gap:10},back:{width:48,height:48,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#111827'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#047857'},title:{fontSize:24,fontWeight:'900',color:'#111827'},body:{padding:16,gap:10,paddingBottom:45},stats:{flexDirection:'row',gap:8},stat:{flex:1,minHeight:88,padding:10,borderRadius:13,borderWidth:2,borderColor:'#D1D5DB',backgroundColor:'#FFF',justifyContent:'center'},num:{fontSize:24,fontWeight:'900',color:'#111827'},statLabel:{fontSize:11,lineHeight:15,color:'#4B5563',fontWeight:'700'},actions:{flexDirection:'row',gap:8},action:{flex:1,minHeight:50,borderRadius:11,backgroundColor:'#047857',alignItems:'center',justifyContent:'center'},actionText:{color:'#FFF',fontWeight:'900'},section:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#6B7280',marginTop:9},card:{padding:14,borderWidth:2,borderColor:'#D1D5DB',borderRadius:12,backgroundColor:'#FFF'},cardTitle:{fontSize:16,fontWeight:'900',color:'#111827'},help:{fontSize:13,color:'#4B5563',marginTop:4},meta:{fontSize:11,color:'#6B7280',marginTop:7},empty:{fontSize:14,color:'#6B7280',padding:20,textAlign:'center'}});
